### ISSUE TITLE
About the prebuilt wheel

### ISSUE THREAD

**Issue by HomieZYJ** [cansik/mediapipe-extended#2]
Hello, I have finished the installation step and have installed the wheel for **linux** and **python3.8**,
but when I run the FaceGeometryExample.py, there was a bug showing below
```shell
Traceback (most recent call last):
  File "FaceGeometryExample.py", line 6, in <module>
    import mediapipe as mp
  File "/home1/z/anaconda3/envs/pose/lib/python3.8/site-packages/mediapipe/__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "/home1/z/anaconda3/envs/pose/lib/python3.8/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: libpng16.so.16: cannot open shared object file: No such file or directory
``` 
I'll appreciate very much if I can get some helps from you

**Comment by cansik** [comment]
Hi, I did not test it on linux a lot, but is libpng16 installed?

sudo apt-get install libpng16-16

**Comment by HomieZYJ** [comment]
> Hi, I did not test it on linux a lot, but is libpng16 installed?
> 
> sudo apt-get install libpng16-16

yeah, I I ignored this question， thanks a lot
after that, another problem is nearly the same
```shell
ImportError: libImath-2_3.so.24: cannot open shared object file: No such file or directory
``` 
but when I went to install the library, it seemed that I cannot install the corresponding version of the library because of the missing version of libimbase. Can I ask for the installation instructions? Thank you very much

**Comment by cansik** [comment]
No I don't have an install instruction for linux, you can have a look at the mediapipe installation for help: https://developers.google.com/mediapipe/framework/getting_started/install

**Comment by Carry-rrk** [comment]
> > Hi, I did not test it on linux a lot, but is libpng16 installed?
> > sudo apt-get install libpng16-16
> 
> yeah, I I ignored this question， thanks a lot after that, another problem is nearly the same
> 
> ```shell
> ImportError: libImath-2_3.so.24: cannot open shared object file: No such file or directory
> ```
> 
> but when I went to install the library, it seemed that I cannot install the corresponding version of the library because of the missing version of libimbase. Can I ask for the installation instructions? Thank you very much

hello, i met same issue, i found it's the problem of resource, change the resource or just use webcam will work
